name: NASA Project CI
on: # trigger events for Pipeline
  push:
    branches: [master] # trigger Pipeline for push requests on master branch
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run build --prefix client
